// Paddle Server-Side API Utilities
// Use this in your backend/Edge Functions

const PADDLE_API_URL = 'https://api.paddle.com/v1';

const headers = {
  'Content-Type': 'application/json',
  'Authorization': `Bearer ${process.env.PADDLE_API_KEY}`,
};

interface FetchOptions {
  method?: string;
  body?: Record<string, unknown>;
}

async function paddleFetch(endpoint: string, options: FetchOptions = {}) {
  const url = `${PADDLE_API_URL}${endpoint}`;
  
  const response = await fetch(url, {
    method: options.method || 'GET',
    headers,
    ...(options.body && { body: JSON.stringify(options.body) }),
  });

  if (!response.ok) {
    throw new Error(`Paddle API error: ${response.statusText}`);
  }

  return response.json();
}

// Customers
export async function createCustomer(email: string, name?: string) {
  return paddleFetch('/customers', {
    method: 'POST',
    body: {
      email,
      name,
      locale: 'en',
    },
  });
}

export async function getCustomer(customerId: string) {
  return paddleFetch(`/customers/${customerId}`);
}

export async function updateCustomer(customerId: string, data: Record<string, unknown>) {
  return paddleFetch(`/customers/${customerId}`, {
    method: 'PATCH',
    body: data,
  });
}

// Subscriptions
export async function createSubscription(customerId: string, priceId: string, billingDetails?: any) {
  return paddleFetch('/subscriptions', {
    method: 'POST',
    body: {
      customer_id: customerId,
      items: [{ price_id: priceId }],
      billing_details: billingDetails,
    },
  });
}

export async function getSubscription(subscriptionId: string) {
  return paddleFetch(`/subscriptions/${subscriptionId}`);
}

export async function updateSubscription(subscriptionId: string, data: Record<string, unknown>) {
  return paddleFetch(`/subscriptions/${subscriptionId}`, {
    method: 'PATCH',
    body: data,
  });
}

export async function pauseSubscription(subscriptionId: string, effectiveFrom?: string) {
  return paddleFetch(`/subscriptions/${subscriptionId}/pause`, {
    method: 'POST',
    body: effectiveFrom ? { effective_from: effectiveFrom } : {},
  });
}

export async function resumeSubscription(subscriptionId: string, effectiveFrom?: string) {
  return paddleFetch(`/subscriptions/${subscriptionId}/resume`, {
    method: 'POST',
    body: effectiveFrom ? { effective_from: effectiveFrom } : {},
  });
}

export async function cancelSubscription(subscriptionId: string, effectiveFrom?: string) {
  return paddleFetch(`/subscriptions/${subscriptionId}/cancel`, {
    method: 'POST',
    body: effectiveFrom ? { effective_from: effectiveFrom } : {},
  });
}

// Transactions
export async function getTransaction(transactionId: string) {
  return paddleFetch(`/transactions/${transactionId}`);
}

export async function listTransactions(customerId?: string, limit: number = 50) {
  let query = `?limit=${limit}`;
  if (customerId) {
    query += `&customer_id=${customerId}`;
  }
  return paddleFetch(`/transactions${query}`);
}

// Prices/Products
export async function getPrice(priceId: string) {
  return paddleFetch(`/prices/${priceId}`);
}

export async function listPrices(productId?: string, limit: number = 50) {
  let query = `?limit=${limit}`;
  if (productId) {
    query += `&product_id=${productId}`;
  }
  return paddleFetch(`/prices${query}`);
}

export async function getProduct(productId: string) {
  return paddleFetch(`/products/${productId}`);
}

export async function listProducts(limit: number = 50) {
  return paddleFetch(`/products?limit=${limit}`);
}

// Checkout
export async function createCheckoutLink(data: {
  items: Array<{ product_id?: string; price_id?: string; quantity?: number }>;
  customer_email?: string;
  custom_data?: Record<string, unknown>;
  return_url?: string;
}) {
  // Note: This is a simplified example. In practice, you'd create this via the dashboard
  // or use the Paddle Checkout API
  return {
    checkout_url: `https://checkout.paddle.com/p/...`, // This would be generated by Paddle
  };
}

// Verification (for webhook validation)
export function verifyWebhookSignature(
  body: string,
  signature: string,
  webhookSecret: string
): boolean {
  const crypto = require('crypto');
  const hash = crypto
    .createHmac('sha256', webhookSecret)
    .update(body)
    .digest('hex');
  
  return hash === signature;
}
